
image: node:7.7.2

before_script:
  - npm update --silent > /dev/null
  - npm install --silent -g tape > /dev/null
  - npm install --silent -g faucet > /dev/null

unit_tests:
  script:
    - tape tests/*.js | faucet
