stages:
  - test
  - build

variables:
  CONTAINER_TEST_IMAGE: git.mygait.com:4567/cgaspard/seemeless:qalatest
  CONTAINER_RELEASE_IMAGE: git.mygait.com:4567/cgaspard/seemeless:latest

image: node:7.7.2

unit_tests:
  stage: test
  before_script:
    - npm update --silent > /dev/null
    - npm install --silent -g tape > /dev/null
    - npm install --silent -g faucet > /dev/null
  script:
    - tape tests/*.js | faucet

build-qa-container:
  stage: build
  before_script:
    - docker info
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.mygait.com:4567
    - docker build --file .dockerfile -t qalatest .
    - docker push $CONTAINER_TEST_IMAGE:qalatest
  only:
    - dev

build-staging-container:
  stage: build
  before_script:
    - docker info
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.mygait.com:4567
    - docker build --file .dockerfile -t latest .
    - docker push $CONTAINER_RELEASE_IMAGE:latest
  only: 
    - master