stages:
  - test
  - build
  - deploy

variables:
  CONTAINER_INTERNAL_PORT: "8080"
  TEST_IMAGE_CONTAINER: "git.mygait.com:4567/cgaspard/seemless"
  TEST_TAG: "qalatest"
  TEST_EXTERNAL_PORT: "9001"
  TEST_CONTAINER_NAME: "seemless-qa"
  RELEASE_IMAGE_CONTAINER: "git.mygait.com:4567/cgaspard/seemless"
  RELEASE_TAG: "latest"
  RELEASE_EXTERNAL_PORT: "9002"
  RELEASE_CONTAINER_NAME: "seemless-staging"

unit_tests:
  stage: test
  image: node:7.7.2
  before_script:
    - npm update --silent > /dev/null
    - npm install --silent -g tape > /dev/null
    - npm install --silent -g faucet > /dev/null
  script:
    - tape tests/*.js | faucet
  tags:
    - nodejs-7.7.2	

build-qa-container:
  stage: build
  before_script:
    - docker info
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.mygait.com:4567
    - docker build --file .dockerfile -t $TEST_TAG .
    - docker push $TEST_IMAGE_CONTAINER:$TEST_TAG
  only:
    - dev
  tags:
    - shell

build-staging-container:
  stage: build
  before_script:
    - docker info
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.mygait.com:4567
    - docker build --file .dockerfile -t $RELEASE_TAG .
    - docker push $RELEASE_IMAGE_CONTAINER:$RELEASE_TAG
  only: 
    - master
  tags:
    - shell

deploy-qa-container:
  stage: deploy
  environment: 
    name: qa
    url: http://172.24.32.6:$TEST_EXTERNAL_PORT/
  before_script:
    - docker info
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.mygait.com:4567  
    - docker pull $TEST_IMAGE_CONTAINER:$TEST_TAG
    - docker stop $TEST_CONTAINER_NAME || true && docker rm $TEST_CONTAINER_NAME || true
    - docker run --name=$TEST_CONTAINER_NAME --restart=always -p 9001:8080  -d $TEST_IMAGE_CONTAINER:$TEST_TAG
  only:
    - dev
  tags:
    - shell
  when: manual

deploy-staging-container:
  stage: deploy
  environment: 
    name: staging
    url: http://172.24.32.6:$RELEASE_EXTERNAL_PORT/
  before_script:
    - docker info
  script: 
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN git.mygait.com:4567  
    - docker pull $RELEASE_IMAGE_CONTAINER:$RELEASE_TAG
    - docker stop $RELEASE_CONTAINER_NAME || true && docker rm $RELEASE_CONTAINER_NAME || true
    - docker run --name=$RELEASE_CONTAINER_NAME --restart=always -p 9002:8080  -d $RELEASE_IMAGE_CONTAINER:$RELEASE_TAG
  only:
    - master
  tags:
    - shell
  when: manual
